name: Monitor de Gas Natural

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Copiar o codigo
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar pacotes
      run: |
        python -m pip install --upgrade pip
        pip install yfinance pandas

    - name: Executar Script
      run: python analise_gas.py
